
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 26 11:43:09 BST 2019
//----------------------------------------------------

package uk.ac.ncl.prime.sim.lang.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BOOL = 6;
  public static final int OP_MIN = 32;
  public static final int REAL = 79;
  public static final int RSQB = 5;
  public static final int B_LAMBDA = 71;
  public static final int OP_MUL = 16;
  public static final int OP_MOD = 26;
  public static final int OP_MINUS = 15;
  public static final int OP_RAN = 40;
  public static final int OP_GEN_INTER = 31;
  public static final int OP_PFUN = 72;
  public static final int OP_EMPTYSET = 47;
  public static final int MAGIC_SUB = 78;
  public static final int OP_EMPTYSEQ = 62;
  public static final int OP_DIV = 20;
  public static final int OP_PINJ = 75;
  public static final int OP_MAX = 33;
  public static final int BCMEQ = 63;
  public static final int OP_RANSUB = 37;
  public static final int OP_SETMINUS = 27;
  public static final int B_FORALL = 68;
  public static final int OP_DOT = 65;
  public static final int B_EXISTS = 69;
  public static final int OP_MAP = 17;
  public static final int OP_RANGE = 53;
  public static final int OP_PRIME = 66;
  public static final int OP_DOM = 41;
  public static final int OP_SOME = 56;
  public static final int OP_FINITE = 76;
  public static final int BCMSUCH = 77;
  public static final int OP_DIRECT_PRODUCT = 80;
  public static final int OP_LSS = 21;
  public static final int NUMBER = 82;
  public static final int OP_DOMSUB = 46;
  public static final int OP_INTER = 39;
  public static final int VLINE = 70;
  public static final int QUESTION = 81;
  public static final int UNIT = 13;
  public static final int LPAR = 2;
  public static final int OP_REL = 73;
  public static final int TYPE_REAL = 8;
  public static final int SEMIC = 61;
  public static final int OP_CARD = 42;
  public static final int OP_FCOMP = 35;
  public static final int ELSE = 12;
  public static final int OP_CONVERSE = 38;
  public static final int OP_COMMA = 58;
  public static final int INT = 7;
  public static final int OP_NEQ = 49;
  public static final int OP_IMPLIES = 67;
  public static final int EOF = 0;
  public static final int OP_AND = 50;
  public static final int OP_GEN_UNION = 30;
  public static final int RPAR = 3;
  public static final int LCUR = 59;
  public static final int OP_LEQ = 23;
  public static final int OP_FALSE = 19;
  public static final int OP_GRT = 22;
  public static final int XTAG = 85;
  public static final int SET = 10;
  public static final int OP_SUBSETEQ = 45;
  public static final int error = 1;
  public static final int OP_PRJ2 = 55;
  public static final int OP_PRJ1 = 54;
  public static final int SEQ = 9;
  public static final int IF = 11;
  public static final int ID = 83;
  public static final int RCUR = 60;
  public static final int OP_OVR = 29;
  public static final int OP_RANRES = 36;
  public static final int OP_GEQ = 25;
  public static final int OP_SUBSET = 44;
  public static final int OP_NOTIN = 74;
  public static final int LSQB = 4;
  public static final int OP_SUM = 34;
  public static final int STRING = 84;
  public static final int OP_UNION = 28;
  public static final int UMINUS = 64;
  public static final int OP_IN = 57;
  public static final int CART = 52;
  public static final int OP_OR = 51;
  public static final int OP_DOMRES = 43;
  public static final int OP_TRUE = 18;
  public static final int OP_EQL = 48;
  public static final int OP_NOT = 24;
  public static final int OP_PLUS = 14;
}

