
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 10 21:28:36 GMT 2019
//----------------------------------------------------

package uk.ac.ncl.safecap.xtype;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OP_PRIME = 11;
  public static final int OP_SEQ = 4;
  public static final int INTEGER = 7;
  public static final int BOOL = 9;
  public static final int ERROR = 10;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int OP_STAR = 6;
  public static final int RBRACKET = 3;
  public static final int ID = 12;
  public static final int REAL = 8;
  public static final int error = 1;
  public static final int OP_POW = 5;
  public static final int LBRACKET = 2;
}

