
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 26 11:45:17 BST 2019
//----------------------------------------------------

package uk.ac.ncl.safecap.lldl;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ERROR = 14;
  public static final int SEMI_COLON = 12;
  public static final int COLON = 11;
  public static final int ID = 16;
  public static final int RCUR = 5;
  public static final int STRING = 17;
  public static final int COMMA = 13;
  public static final int LCUR = 4;
  public static final int EOF = 0;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int DOUBLE_COLON = 10;
  public static final int INTEGER = 15;
  public static final int RPAR = 3;
  public static final int AND4 = 8;
  public static final int REAL = 18;
  public static final int AND3 = 7;
  public static final int AND2 = 6;
  public static final int LPAR = 2;
}

