
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 06 11:16:51 BST 2019
//----------------------------------------------------

package uk.ac.ncl.safecap.cteparser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RCUR = 5;
  public static final int LSQB = 6;
  public static final int LPAR = 2;
  public static final int XERROR = 8;
  public static final int EOF = 0;
  public static final int LCUR = 4;
  public static final int RSQB = 7;
  public static final int error = 1;
  public static final int RPAR = 3;
  public static final int MAGIC2 = 10;
  public static final int MAGIC1 = 9;
  public static final int TOKEN = 11;
}

