
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 11 18:39:22 BST 2019
//----------------------------------------------------

package uk.ac.ncl.safecap.textentry.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RQT = 15;
  public static final int RSQB = 7;
  public static final int XFALSE = 9;
  public static final int COLON = 11;
  public static final int ID = 18;
  public static final int LSQB = 6;
  public static final int RCUR = 5;
  public static final int STRING = 19;
  public static final int SEMIC = 12;
  public static final int COMMA = 13;
  public static final int LCUR = 4;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int XTRUE = 8;
  public static final int error = 1;
  public static final int META = 14;
  public static final int RPAR = 3;
  public static final int REAL = 17;
  public static final int LPAR = 2;
  public static final int XERROR = 10;
}

