
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 13 21:35:05 GMT 2019
//----------------------------------------------------

package uk.ac.ncl.safecap.prover.tactic.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LSS = 10;
  public static final int RCUR = 7;
  public static final int LSQB = 4;
  public static final int BOT = 12;
  public static final int TOP = 11;
  public static final int ERROR = 13;
  public static final int LPAR = 2;
  public static final int STRING = 15;
  public static final int EXC = 8;
  public static final int EOF = 0;
  public static final int LCUR = 6;
  public static final int RSQB = 5;
  public static final int ID = 14;
  public static final int error = 1;
  public static final int INC = 9;
  public static final int RPAR = 3;
}

